export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_USERS = "GET_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const APPOINT_ADMIN = "APPOINT_ADMIN";
export const REMOVE_ADMIN = "REMOVE_ADMIN";

export const GET_FANFIKS = "GET_FANFIKS";
export const GET_FANFIK_FOR_READ = "GET_FANFIK_FOR_READ";
export const CLEAR_READ_FANFIK = "CLEAR_READ_FANFIK";